### ISSUE TITLE
Test results folder is not visible in the project on the IDE

### ISSUE THREAD

**Issue by christopherjohn823** [vdespa/Jenkins-course-support-for-YouTube#1]
Hi,

While going throught Lecture 15, on my IDE I wasn't able to find the test results folder which is supposed to contain the Junit.xml file, as it was shown in the lecture. Although while running the test I didn't get a failure but I am wondering if I have missed any step or have I not transferred the project correctly onto Codespaces

**Comment by vdespa** [comment]
Hi,

Did you open a terminal window and run the commands shown in the course? 

If so, please attach a screenshot. 

Thanks!

**Comment by christopherjohn823** [comment]
Hi Valentin,

Pardon me for the delay in replying. I ran the lectures second time from
1st to the 14th lecture in order to see if I had missed anything. But I am
still not able to see the Test results folder created in the folder
structure after the npm test command is run. I have attached the screenshot
of the IDE.

Thanks.

**Comment by vdespa** [comment]
I am sorry, but I don't see any screenshots. Can you use Github.com to upload that screenshot? Thanks!

**Comment by christopherjohn823** [comment]
<img width="1440" alt="Test results folder not created after npm test command is run_editor screenshot" src="https://github.com/user-attachments/assets/6f147176-cac2-4e48-b187-668244a83d15">
<img width="1440" alt="Test results folder not created after npm test command is run_Terminal screenshot" src="https://github.com/user-attachments/assets/38415ec3-5c32-4548-a439-3354ec6264d0">

**Comment by christopherjohn823** [comment]
Hi Valentin,

Please let me know if you are able to view the screenshots. Thanks

**Comment by vdespa** [comment]
By looking at the logs, I don't see that you have executed the tests. 

These are the log outputs from the build process.
