### ISSUE TITLE
Unable to create an account on Netlify

### ISSUE THREAD

**Issue by christopherjohn823** [vdespa/Jenkins-course-support-for-YouTube#2]
Unable to create an account on Netlify as it is asking for a lot of personal details such as personal documents and id proofs.

**Comment by vdespa** [comment]
Hi,

This is news to me. Can you attach a screenshot please?

**Comment by christopherjohn823** [comment]
Hi Valentin,

Pardon me for the late response. Attaching the screenshot of the issue that
I am facing in opening an account Netlify. Kindly let me know how this can
be resolved.

Thanks.

**Comment by vdespa** [comment]
I am sorry, but I don't see any screenshots. Can you use Github.com to upload that screenshot? Thanks!

**Comment by christopherjohn823** [comment]
<img width="1433" alt="Unable to create an account in Netlify_Jenkins course" src="https://github.com/user-attachments/assets/8cac6886-3139-4461-9f20-d705178be964">
<img width="1436" alt="Email recieved from Netlify" src="https://github.com/user-attachments/assets/7fd9af51-be9e-4af8-a167-9dcf8998fb35">

**Comment by christopherjohn823** [comment]
Hi Valentin,

Please let me know if you are able to view the screenshots attached. Thanks

**Comment by vdespa** [comment]
Thanks for the screenshot. Not sure what happened.

Did you use a VPN when registering? 

Anyway, trying verifying or create a new account.
